language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t blacker/react_test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true blacker/react_test npm test

after_success:
  - docker build -t blacker12/multi-client ./client
  - docker build -t blacker12/multi-nginx ./nginx
  - docker build -t blacker12/multi-server ./server
  - docker build -t blacker12/multi-worker ./worker
  # login into the docker CLI 
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
  # take those images and push to docker hub
  - docker push blacker12/multi-client
  - docker push blacker12/multi-nginx
  - docker push blacker12/multi-server
  - docker push blacker12/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-660753416379'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY